### ISSUE TITLE
What does this project do?

### ISSUE THREAD

**Issue by josegonzalez** [marc-barry/007#16]
Serious question, as I noticed you contributed to [goprocinfo](https://github.com/c9s/goprocinfo) and I'm currently screwing around with golang to replace [diamond](https://github.com/python-diamond/Diamond) as a metrics collector.

**Comment by marc-barry** [comment]
Sorry. I somehow missed you comment.

I have not added any docs to the project yet. Basically, we are using this project to collect certain metrics from the Linux host. With a focus on networking stats but that is only because that is the ones most important for my use case at this time.

Indeed, it does use [goprocinfo](https://github.com/c9s/goprocinfo) to collect the stats. These stats then get logged to `stdout` and a filtered set get sent to `DogStatsD`.

I'll get some docs up soon. As really the only way to understand the project right now is via the source code :disappointed:.

**Comment by marc-barry** [comment]
Here's an example of the command line arguments:

```
007 \
  -http-enable \
  -http-port=9300 \
  -dogstatsd-address=localhost:8125 \
  -stats-interface-filter=^veth \
  -stats=RxBytes,RxPackets,TxBytes,TxPackets,SyncookiesSent,SyncookiesRecv,SyncookiesFailed,PruneCalled,RcvPruned,OfoPruned,ListenOverflows,ListenDrops,TCPForwardRetrans,TCPSlowStartRetrans,TCPLossProbes,TCPLossProbeRecovery,TCPDSACKOfoRecv,TCPTimeouts,TCPRcvCollapsed,TCPAbortOnMemory,TCPBacklogDrop,TCPDeferAcceptDrop,TCPTimeWaitOverflow,TCPReqQFullDrop,TCPOFODrop,TCPSynRetrans,TW,TWRecycled,TWKilled,SocketsUsed,TCPInUse,TCPTimeWait,UDPInUse \
  -calculate-rate=2 \
  -collect-rate=2 \
  -log-rate=10 \
  -json-log \
```

The above assumes that `DogStatsD` is running on localhost. `stats` are the list of metrics being collected. `007 -h` will dump all the supported stats to `stdout`.

**Comment by josegonzalez** [comment]
Gotcha. I'm actually looking at writing [something similar](https://github.com/josegonzalez/metricsd), though our interfaces and configuration are a bit different. Was just curious as to how this works :)
